---
  team_mappings:
    Engineering: 0
    Data: 10
    Product: 20
    Design: 30
    Marketing: 40
    Outreach: 50
    Community Support: 60
    Integrity: 70
    Communications: 80
    Operations: 90
    Exec: 110
  tenure_weight: 0.2
  team_weight: 0.9
  manager_weight: 1.0
  colleague_weight: 1.0
  previous_lunches_weight: 1.0
  previous_lunches_half_life: 3.0
  min_lunch_group_size: 5
  max_group_score: 0.0001
